/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class HomeUI extends Scene {
		public num_txt:Laya.FontClip;
		public selectBg:Laya.Sprite;
		public btnDevice:Laya.Sprite;
		public btnExchange:Laya.Sprite;
		public btnRank:Laya.Sprite;
		public btnMe:Laya.Sprite;
		public out_txt:Laya.TextArea;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Home");
        }
    }
    REG("ui.HomeUI",HomeUI);
}