export default class Langue extends Laya.EventDispatcher {
    public static defaultLangue:any
    public static cn = {
        start:'开始',
        ok: '确定',
        close: '关闭',
        notice_0:'等待矿工派出设备',
        notice: '公告',
        email: '邮件',
        chat: '聊天',
        help: '帮助',
        home_0: '我知道了',
        home_1: '一键领取',
        home_2: '一键读取',
        nav1: '设备',
        nav2: '交易',
        nav3: '排行',
        nav4: '我的',
        nav1_1: '低 → 高',
        nav1_2: '高 → 低',
        nav1_3: '全选',
        nav1_4: '自动匹配',
        nav1_5: '总载重',
        nav1_6: '总挖矿',
        nav1_7: '预计收益',
        nav1_8: '开始挖矿',
        nav3_0: '当前TOP10',
        nav3_1: '当前TOP50',
        nav3_2: '全网TOP50',
        nav3_3: '排名',
        nav3_4: '账号',
        nav3_5: '运走量',
        nav4_1: '基本信息',
        nav4_2: '我的收益',
        nav4_3: '返佣明细',
        nav4_4: '昵称',
        nav4_4_1:'保存',
        nav4_5: '我的地址',
        nav4_6: '钱包',
        nav4_7: '邀请链接',
        nav4_8: '复制',
        nav5_1: '期数',
        nav5_2: '派出设备',
        nav5_3: '收益(ETH/CM)',
        nav5_4: '领取',
        nav5_5: '未领取',
        nav6_1: '昵称',
        nav6_2: '地址',
        nav6_3: '奖励',

        nav7_1:'en设备详情：',
        nav7_2:'en载重/挖矿：',
        nav7_3:'en等级：'

    }
    public static en = {
        start:'start',
        ok: 'OK',
        close: 'Close',
        notice_0:'wait...',
        notice: 'Notice',
        email: 'Mail',
        chat: 'Chat',
        help: 'Help',
        home_0: 'I got it',
        home_1: 'receive',
        home_2: 'reading',
        nav1: 'device',
        nav2: 'transaction',
        nav3: 'ranking',
        nav4: 'mine',
        nav1_1: 'low->High',
        nav1_2: 'High->low',
        nav1_3: 'Select all',
        nav1_4: 'Automatic',
        nav1_5: 'load',
        nav1_6: 'mining',
        nav1_7: 'income',
        nav1_8: 'Start',
        nav3_0: 'currentTOP10',
        nav3_1: 'currentTOP50',
        nav3_2: 'networkTOP50',
        nav3_3: 'rank',
        nav3_4: 'Account',
        nav3_5: 'volume',
        nav4_1: 'Basic',
        nav4_2: 'My',
        nav4_3: 'Rebate',
        nav4_4: 'nickname',
        nav4_4_1:'save',
        nav4_5: 'Address',
        nav4_6: 'Wallet',
        nav4_7: 'Invitation',
        nav4_8: 'copy',
        nav5_1: '期数e',
        nav5_2: '派出设备e',
        nav5_3: '收益(ETH/CM)e',
        nav5_4: '领取e',
        nav5_5: '未领取e',
        nav6_1: '昵称e',
        nav6_2: '地址e',
        nav6_3: '奖励e',
        alert1:'please ...',
        nav7_1:'设备详情：',
        nav7_2:'载重/挖矿：',
        nav7_3:'等级：'
    }
    public static kr = {
        start:'start',
        ok: '확인',
        close: '닫기',
        notice: '발표',
        notice_0:'wait...',
        email: '우편',
        chat: '채팅',
        help: '도움말',
        home_0: '알았어요',
        home_1: '수신 할 하나의 열쇠',
        home_2: '원키 읽기',
        nav1: '장치',
        nav2: '트랜잭션',
        nav3: '순위',
        nav4: '나의 것',
        nav1_1: '낮은',
        nav1_2: '높음',
        nav1_3: '모두 선택',
        nav1_4: '자동 일치',
        nav1_5: '총 부하',
        nav1_6: '총 채굴',
        nav1_7: '예상 수입',
        nav1_8: '채굴 시작',
        nav3_1: '현재',
        nav3_2: '전체 네트워크',
        nav3_3: '순위',
        nav3_4: '계정',
        nav3_5: '배송량',
        nav4_1: '기본 정보',
        nav4_2: '내 수입',
        nav4_3: '환급 내역',
        nav4_4: '별명',
        nav4_4_1:'save',
        nav4_5: '내 주소',
        nav4_6: '지갑',
        nav4_7: '초대 링크',
        nav4_8: '복사',
        nav5_1: '期数',
        nav5_2: '派出设备',
        nav5_3: '收益(ETH/CM)',
        nav5_4: '领取',
        nav5_5: '未领取',
        nav6_1: '昵称',
        nav6_2: '地址',
        nav6_3: '奖励',
        alert1:'please ...',
        nav7_1:'设备详情：',
        nav7_2:'载重/挖矿：',
        nav7_3:'等级：'
    }

    constructor() {
        super();
    }

    public static setLanguage(lang:string){
        if(lang=='zh-CN'){
            Langue.defaultLangue=Langue.cn
        }else if(lang=='en-US'){
            Langue.defaultLangue=Langue.en
        }else if(lang=='kr'){
            Langue.defaultLangue=Langue.kr
        }
    }

}