export default class Langue extends Laya.EventDispatcher {
    public static defaultLangue: any
    public static cn = {
        start: '开始',
        ok: '确定',
        close: '关闭',
        notice_0: '等待矿工派出设备',
        notice: '公告',
        email: '邮件',
        chat: '聊天',
        help: '帮助',
        home_0: '我知道了',
        home_1: '一键领取',
        home_2: '一键读取',
        nav1: '设备',
        nav2: '市场',
        nav3: '排行',
        nav4: '我的',
        nav1_1: '低 → 高',
        nav1_2: '高 → 低',
        nav1_3: '全选',
        nav1_4: '自动匹配',
        nav1_5: '总载重：',
        nav1_6: '总挖矿：',
        nav1_7: '总车辆：',
        nav1_8: '开始挖矿',
        nav3_0: '当前TOP10',
        nav3_1: '当前TOP50',
        nav3_2: '全网TOP50',
        nav3_3: '排名',
        nav3_4: '账号',
        nav3_5: '运走量',
        nav4_1: '基本信息',
        nav4_2: '我的收益',
        nav4_3: '返佣明细',
        nav4_4: '昵称',
        nav4_4_1: '保存',
        nav4_5: '我的地址',
        nav4_6: '资产',
        nav4_7: '邀请链接',
        nav4_8: '复制',
        nav5_1: '期数',
        nav5_2: '派出设备',
        nav5_3: '收益(ETH)',
        nav5_4: '已领取',
        nav5_5: '未领取',
        nav5_6: '已发放',
        nav5_7: '未发放',
        nav6_1: '昵称',
        nav6_2: '地址',
        nav6_3: '奖励',

        nav7_1: '设备详情：',
        nav7_2: '载重：',
        nav7_2_1:'挖矿：',
        nav7_3: '等级：',

        nav8_0: '派出记录',
        nav8_1: '总派出',
        nav8_2: '总挖矿',
        nav8_3: '总运走',

        setTitle: '设置',
        musicSet: '音效设置',
        music: '音乐',
        sound: '音效',
        gasSet: '手续费',
        langSet: '语言设置',
        onOff: '开          ,关',
        waitTip:'设备就绪等待发车',
        verify:'验证',
        lastHit:'完成了最后一击',
        copySuccess:'复制成功'
    }
    public static en = {
        start: 'start',
        ok: 'OK',
        close: 'Close',
        notice_0: 'Waiting to dispatch equipment',
        notice: 'Notice',
        email: 'Mail',
        chat: 'Chat',
        help: 'Help',
        home_0: 'I got it',
        home_1: 'receive',
        home_2: 'reading',
        nav1: 'Equipment',
        nav2: 'Market',
        nav3: 'Ranking',
        nav4: 'My',
        nav1_1: 'low->High',
        nav1_2: 'High->low',
        nav1_3: 'All',
        nav1_4: 'Automatic',
        nav1_5: 'load',
        nav1_6: 'mining',
        nav1_7: '总车辆：',
        nav1_8: 'Start',
        nav3_0: 'Current TOP10',
        nav3_1: 'Current TOP50',
        nav3_2: 'All TOP50',
        nav3_3: 'Rank',
        nav3_4: 'Account',
        nav3_5: 'Volume',
        nav4_1: 'Information',
        nav4_2: 'Income',
        nav4_3: 'Rebate',
        nav4_4: 'Nick',
        nav4_4_1: 'Save',
        nav4_5: 'My Address',
        nav4_6: 'Assets',
        nav4_7: 'Referral',
        nav4_8: 'Copy',
        nav5_1: 'Round',
        nav5_2: 'Equipment ',
        nav5_3: 'Income(ETH)',
        nav5_4: 'collect',
        nav5_5: 'not received',
        nav5_6: 'issued',
        nav5_7: 'Unreleased',
        nav6_1: 'Nick',
        nav6_2: 'Address',
        nav6_3: 'Bonus ',
        alert1: 'please ...',
        nav7_1: 'Detail: ',
        nav7_2: 'Load:',
        nav7_2_1: 'Mining:',
        nav7_3: 'level:',
        nav8_0: 'Dispatch record',
        nav8_1: 'Always dispatched',
        nav8_2: 'Total mining',
        nav8_3: 'total transport',
        setTitle: 'Setting',
        musicSet: 'Sound',
        music: 'Music',
        sound: 'Sound',
        gasSet: 'Gas',
        langSet: 'Language',
        onOff: 'ON         ,OFF',
        waitTip:'Preparing for mining',
        verify:'verify',
        lastHit:'完成了最后一击',
        copySuccess:'success'
    }
    public static kr = {
        start: 'start',
        ok: '확인',
        close: '닫기',
        notice: '공지',
        notice_0: '마이닝 설비 대기중',
        email: '메일',
        chat: '채팅',
        help: '도움말',
        home_0: '알았어요',
        home_1: '수신 할 하나의 열쇠',
        home_2: '원키 읽기',
        nav1: '설비',
        nav2: '마켓',
        nav3: '순위',
        nav4: '나의',
        nav1_1: '낮은',
        nav1_2: '높음',
        nav1_3: '모두선택',
        nav1_4: '자동매칭',
        nav1_5: '총 부하',
        nav1_6: '총 채굴',
        nav1_7: '总车辆',
        nav1_8: '채굴 시작',

        nav3_0: '현재 탑10',
        nav3_1: '현재 탑50',
        nav3_2: '전체 탑50',

        nav3_3: '순위',
        nav3_4: '계정',
        nav3_5: '볼륨',
        nav4_1: '기본정보',
        nav4_2: '수익내역',
        nav4_3: '추천내역',
        nav4_4: '닉네임',
        nav4_4_1: '확인',
        nav4_5: '나의 주소',
        nav4_6: '자산',
        nav4_7: '추천링크',
        nav4_8: '복사',
        nav5_1: '회차',
        nav5_2: "설비수량",
        nav5_3: '수익(ETH)',
        nav5_4: "수령",
        nav5_5: "미 수령",
        nav5_6: '발행 됨',
        nav5_7: '출시되지 않음',
        nav6_1: "닉네임",
        nav6_2: "주소",
        nav6_3: "보너스",
        alert1: "please...",
        nav7_1: '자세히',
        nav7_2: "적재량:",
        nav7_2_1: '마이닝:',
        nav7_3: "등급:",
        nav8_0: '파견 기록',
        nav8_1: '항상 파견 됨',
        nav8_2: '총 채굴',
        nav8_3: '총 이동 거리',
        setTitle: '설정',
        musicSet: '사운드',
        music: '음악',
        sound: '사운드',
        gasSet: 'Gas',
        langSet: '언어 설정',
        onOff: '켜기          ,끄기',
        waitTip:'마이닝 준비중',
        verify:'verify',
        lastHit:'完成了最后一击',
        copySuccess:'success'
    }

    constructor() {
        super();
    }

    public static setLanguage(lang: string) {
        if (lang == 'zh-CN') {
            Langue.defaultLangue = Langue.cn
        } else if (lang == 'en-US') {
            Langue.defaultLangue = Langue.en
        } else if (lang == 'kr') {
            Langue.defaultLangue = Langue.kr
        }
    }

}
